{% set version = "0.1.0" %}

package:
  name: lnad
  version: {{ version }}

source:
  git_url: https://github.com/stigrs/lnad.git

build:
  noarch: python
  number: 0
  script: python -m pip install .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - networkx
    - igraph
    - pycairo
    - matplotlib
    - pandas
    - geopandas
    - momepy
    - contextily
    - pathlib
    - shapely

about:
  home: https://github.com/stigrs/lnad
  license: MIT
  summary: "Library for network analysis and dismantling."
  description: |
    Library for network analysis and dismantling.
  dev_url: https://github.com/stigrs/lnad
